// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProductRule.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductionCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProductDetail", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShippingCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("ProductRuleMatch", b =>
                {
                    b.Property<int>("ProductRuleMatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RuleDefinitionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductRuleMatchId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RuleDefinitionId");

                    b.ToTable("ProductRuleMatches");
                });

            modelBuilder.Entity("ProductTest", b =>
                {
                    b.Property<int>("ProductTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductTestId");

                    b.ToTable("ProductTests");
                });

            modelBuilder.Entity("RuleDefinition", b =>
                {
                    b.Property<int>("RuleDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductTestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductionCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingCountry")
                        .HasColumnType("TEXT");

                    b.HasKey("RuleDefinitionId");

                    b.HasIndex("ProductTestId");

                    b.ToTable("RuleDefinitions");
                });

            modelBuilder.Entity("ProductDetail", b =>
                {
                    b.HasOne("Product", null)
                        .WithOne("Detail")
                        .HasForeignKey("ProductDetail", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductRuleMatch", b =>
                {
                    b.HasOne("Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuleDefinition", "RuleDefinition")
                        .WithMany()
                        .HasForeignKey("RuleDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("RuleDefinition");
                });

            modelBuilder.Entity("RuleDefinition", b =>
                {
                    b.HasOne("ProductTest", "ProductTest")
                        .WithMany()
                        .HasForeignKey("ProductTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductTest");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Navigation("Detail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
